spring.application.name=sentinel
# Enable Virtual Threads for high-performance cloud operations
spring.threads.virtual.enabled=true
# Spring AI Gemini Configuration
spring.ai.google.genai.api-key=AIzaSyA5uRxbsSEbQOKLz6rfihhm3w8yU2Xqzvk
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=sentinel
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true